// <auto-generated />
using System;
using AssetManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717143748_statusTransition_seeded6")]
    partial class statusTransition_seeded6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.AssetKinds.AssetKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasMacAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<bool>("IsPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AssetKinds", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.AssetTypes.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetKindId")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DepreciationPeriod")
                        .HasColumnType("int");

                    b.Property<int>("DepreciationValue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("JiraId")
                        .HasColumnType("int");

                    b.Property<bool>("MobileEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrefixName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Requestable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<bool>("SecuritySensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("AssetKindId");

                    b.HasIndex("ModelId");

                    b.ToTable("AssetTypes", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CmdbLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("DepreciationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DisposedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MsLicenceMappingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Manufacturers.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Requestable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Requestable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.StatusTransitions.StatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StatusFromId")
                        .HasColumnType("int");

                    b.Property<int>("StatusToId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusFromId = 1,
                            StatusToId = 6
                        },
                        new
                        {
                            Id = 2,
                            StatusFromId = 1,
                            StatusToId = 3
                        },
                        new
                        {
                            Id = 3,
                            StatusFromId = 2,
                            StatusToId = 3
                        },
                        new
                        {
                            Id = 4,
                            StatusFromId = 2,
                            StatusToId = 4
                        },
                        new
                        {
                            Id = 5,
                            StatusFromId = 2,
                            StatusToId = 6
                        },
                        new
                        {
                            Id = 6,
                            StatusFromId = 2,
                            StatusToId = 5
                        },
                        new
                        {
                            Id = 7,
                            StatusFromId = 3,
                            StatusToId = 5
                        },
                        new
                        {
                            Id = 8,
                            StatusFromId = 3,
                            StatusToId = 2
                        },
                        new
                        {
                            Id = 9,
                            StatusFromId = 3,
                            StatusToId = 4
                        },
                        new
                        {
                            Id = 10,
                            StatusFromId = 4,
                            StatusToId = 6
                        },
                        new
                        {
                            Id = 11,
                            StatusFromId = 4,
                            StatusToId = 2
                        },
                        new
                        {
                            Id = 12,
                            StatusFromId = 4,
                            StatusToId = 3
                        },
                        new
                        {
                            Id = 13,
                            StatusFromId = 5,
                            StatusToId = 8
                        },
                        new
                        {
                            Id = 14,
                            StatusFromId = 5,
                            StatusToId = 6
                        },
                        new
                        {
                            Id = 15,
                            StatusFromId = 5,
                            StatusToId = 3
                        },
                        new
                        {
                            Id = 16,
                            StatusFromId = 5,
                            StatusToId = 2
                        },
                        new
                        {
                            Id = 17,
                            StatusFromId = 6,
                            StatusToId = 7
                        },
                        new
                        {
                            Id = 18,
                            StatusFromId = 6,
                            StatusToId = 2
                        },
                        new
                        {
                            Id = 19,
                            StatusFromId = 6,
                            StatusToId = 4
                        },
                        new
                        {
                            Id = 20,
                            StatusFromId = 6,
                            StatusToId = 5
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Statuses.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusTransitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CreateAsset",
                            StatusTransitionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stock",
                            StatusTransitionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "InUse",
                            StatusTransitionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "AssetInServiceRepair",
                            StatusTransitionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "ReportedStolenMissing",
                            StatusTransitionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "ObsoleteAsset",
                            StatusTransitionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "AssetDisposed",
                            StatusTransitionId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "AssetLost",
                            StatusTransitionId = 8
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.AssetTypes.AssetType", b =>
                {
                    b.HasOne("AssetManagement.Domain.AssetKinds.AssetKind", null)
                        .WithMany()
                        .HasForeignKey("AssetKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Assets.Asset", b =>
                {
                    b.HasOne("AssetManagement.Domain.Assets.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Models.Model", b =>
                {
                    b.HasOne("AssetManagement.Domain.Manufacturers.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
